export type Category = 'Soft & Fresh' | 'Semi-Dry' | 'Dry' | 'Amber' | 'Processed' | 'Confections'

export type Product = {
  id: string
  name: string
  variety: string
  category: Category
  image: string
  origin: string
  moisture: string
  note: string
  moq: string
}

export const categories: Category[] = [
  'Soft & Fresh',
  'Semi-Dry',
  'Dry',
  'Amber',
  'Processed',
  'Confections',
]

export const products: Product[] = [
  {
    id: 'mazafati-kimia',
    name: 'Kimia Mazafati',
    variety: 'Mazafati',
    category: 'Soft & Fresh',
    image: '/images/date-soft.png',
    origin: 'Bam, Kerman',
    moisture: '~32% moisture',
    note: 'Jet-dark, caramel-soft flesh with notes of chocolate and toffee. Our signature crown jewel.',
    moq: 'MOQ 5 MT',
  },
  {
    id: 'mazafati-bam',
    name: 'Bam Reserve Mazafati',
    variety: 'Mazafati',
    category: 'Soft & Fresh',
    image: '/images/date-soft.png',
    origin: 'Bam, Kerman',
    moisture: '~35% moisture',
    note: 'Cold-chain reserve grade. Plump, glossy, and cool — selected from the first harvest pass.',
    moq: 'MOQ 3 MT',
  },
  {
    id: 'kaluteh',
    name: 'Kaluteh Mazafati',
    variety: 'Mazafati',
    category: 'Soft & Fresh',
    image: '/images/date-soft.png',
    origin: 'Jiroft, Kerman',
    moisture: '~30% moisture',
    note: 'Slightly firmer sibling of Kimia. Deep sweetness with a clean, lingering finish.',
    moq: 'MOQ 5 MT',
  },
  {
    id: 'shahani',
    name: 'Shahani',
    variety: 'Shahani',
    category: 'Soft & Fresh',
    image: '/images/date-soft.png',
    origin: 'Fars',
    moisture: '~28% moisture',
    note: 'Elongated and semi-soft with a honeyed core. A beloved everyday luxury.',
    moq: 'MOQ 5 MT',
  },
  {
    id: 'piarom',
    name: 'Piarom (Maryami)',
    variety: 'Piarom',
    category: 'Semi-Dry',
    image: '/images/date-semidry.png',
    origin: 'Hajiabad, Hormozgan',
    moisture: '~15% moisture',
    note: 'The connoisseur’s date. Long, dark, and semi-dry with an unmistakable dark-sugar depth.',
    moq: 'MOQ 3 MT',
  },
  {
    id: 'rabbi',
    name: 'Rabbi',
    variety: 'Rabbi',
    category: 'Semi-Dry',
    image: '/images/date-semidry.png',
    origin: 'Sistan & Baluchestan',
    moisture: '~18% moisture',
    note: 'Semi-dry, thin-skinned and richly sweet. Excellent shelf life for long freight routes.',
    moq: 'MOQ 5 MT',
  },
  {
    id: 'deglet-noor',
    name: 'Deglet Noor',
    variety: 'Deglet Noor',
    category: 'Semi-Dry',
    image: '/images/date-semidry.png',
    origin: 'Khuzestan',
    moisture: '~20% moisture',
    note: 'Translucent, firm and elegant — the “date of light.” A global retail staple.',
    moq: 'MOQ 5 MT',
  },
  {
    id: 'kabkab',
    name: 'Kabkab',
    variety: 'Kabkab',
    category: 'Semi-Dry',
    image: '/images/date-semidry.png',
    origin: 'Behbahan, Khuzestan',
    moisture: '~22% moisture',
    note: 'Full-bodied and juicy, ideal for paste and syrup as well as table grade.',
    moq: 'MOQ 5 MT',
  },
  {
    id: 'zahedi',
    name: 'Zahedi',
    variety: 'Zahedi',
    category: 'Dry',
    image: '/images/date-dry.png',
    origin: 'Fars & Khuzestan',
    moisture: '~14% moisture',
    note: 'Golden, firm and mildly sweet. The workhorse dry date for industry and export volume.',
    moq: 'MOQ 10 MT',
  },
  {
    id: 'thoory',
    name: 'Thoory (Bread Date)',
    variety: 'Thoory',
    category: 'Dry',
    image: '/images/date-dry.png',
    origin: 'Khuzestan',
    moisture: '~12% moisture',
    note: 'Firm, chewy and low-moisture with a nutty finish. Superb ambient stability.',
    moq: 'MOQ 10 MT',
  },
  {
    id: 'estameran-dry',
    name: 'Estameran',
    variety: 'Estameran',
    category: 'Dry',
    image: '/images/date-dry.png',
    origin: 'Abadan, Khuzestan',
    moisture: '~16% moisture',
    note: 'Semi-dry to dry, deep reddish-brown, engineered for bulk containerized freight.',
    moq: 'MOQ 10 MT',
  },
  {
    id: 'sayer',
    name: 'Sayer (Stamaran)',
    variety: 'Sayer',
    category: 'Amber',
    image: '/images/date-amber.png',
    origin: 'Khuzestan',
    moisture: '~17% moisture',
    note: 'Amber-red and semi-dry — the most exported Iranian date. Pitted or whole.',
    moq: 'MOQ 10 MT',
  },
  {
    id: 'dayri-amber',
    name: 'Dayri',
    variety: 'Dayri',
    category: 'Amber',
    image: '/images/date-amber.png',
    origin: 'Khuzestan',
    moisture: '~19% moisture',
    note: 'Warm amber tone with balanced sweetness. A refined alternative to darker grades.',
    moq: 'MOQ 5 MT',
  },
  {
    id: 'barhi',
    name: 'Barhi',
    variety: 'Barhi',
    category: 'Amber',
    image: '/images/date-amber.png',
    origin: 'Khuzestan',
    moisture: '~24% moisture',
    note: 'Buttery, honey-blonde and prized fresh. Cold-chain shipped for premium retail.',
    moq: 'MOQ 3 MT',
  },
  {
    id: 'date-paste',
    name: 'Date Paste',
    variety: 'Processed',
    category: 'Processed',
    image: '/images/date-paste.png',
    origin: 'Khuzestan mills',
    moisture: 'Std. paste grade',
    note: 'Smooth, pitted date paste for bakery, confection and industrial use. Bulk pails.',
    moq: 'MOQ 5 MT',
  },
  {
    id: 'date-syrup',
    name: 'Date Syrup (Silan)',
    variety: 'Processed',
    category: 'Processed',
    image: '/images/date-syrup.png',
    origin: 'Khuzestan mills',
    moisture: '~75° Brix',
    note: 'Pure, dark date molasses. A natural sweetener for food manufacturers and retail.',
    moq: 'MOQ 5 MT',
  },
  {
    id: 'pitted',
    name: 'Pitted Dates',
    variety: 'Processed',
    category: 'Processed',
    image: '/images/date-soft.png',
    origin: 'Multi-origin',
    moisture: 'By variety',
    note: 'Machine-pitted table grade across Sayer, Zahedi and Kabkab. Retail-ready.',
    moq: 'MOQ 5 MT',
  },
  {
    id: 'chopped',
    name: 'Diced Dates',
    variety: 'Processed',
    category: 'Processed',
    image: '/images/date-semidry.png',
    origin: 'Multi-origin',
    moisture: 'Coated w/ rice flour',
    note: 'Free-flowing diced pieces for cereal, bakery and snack manufacturing.',
    moq: 'MOQ 5 MT',
  },
  {
    id: 'date-sugar',
    name: 'Date Sugar & Powder',
    variety: 'Processed',
    category: 'Processed',
    image: '/images/date-dry.png',
    origin: 'Khuzestan mills',
    moisture: 'Dried & milled',
    note: 'Whole-fruit date sugar — an unrefined sweetener for clean-label formulations.',
    moq: 'MOQ 3 MT',
  },
  {
    id: 'coated',
    name: 'Chocolate & Nut Coated',
    variety: 'Confection',
    category: 'Confections',
    image: '/images/date-coated.png',
    origin: 'Food King atelier',
    moisture: 'Confection grade',
    note: 'Mazafati dates enrobed in dark couverture and crushed pistachio. Gift-ready.',
    moq: 'MOQ 500 kg',
  },
  {
    id: 'stuffed',
    name: 'Nut-Stuffed Dates',
    variety: 'Confection',
    category: 'Confections',
    image: '/images/date-stuffed.png',
    origin: 'Food King atelier',
    moisture: 'Confection grade',
    note: 'Hand-stuffed with whole pistachio, walnut or almond. Presented in luxury trays.',
    moq: 'MOQ 500 kg',
  },
  {
    id: 'gift-collection',
    name: 'The Crown Collection',
    variety: 'Confection',
    category: 'Confections',
    image: '/images/date-coated.png',
    origin: 'Food King atelier',
    moisture: 'Assorted',
    note: 'A curated assortment of our finest grades in a signature presentation box.',
    moq: 'MOQ 250 units',
  },
]
